#访问端口
server:
  port: 18082

spring:
  application:
    name: tanhua-dubbo-mongodb
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.80.166:8848
  data:
    mongodb:
      uri: mongodb://192.168.80.166:27017/tanhua
#dubbo配置
dubbo:
  protocol:
    name: dubbo
    port: 20882
  registry:
    address: spring-cloud://localhost
  scan:
    base-packages: com.tanhua.dubbo.api



